name: library_of_ohara
description: "Proyecto de Flutter: Gestión de Libros"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.5.3

dependencies:
  bcrypt: ^1.1.3
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.5
  provider: ^6.1.2
  sqflite_common_ffi: ^2.3.4+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
  
  fonts:
    - family: SedgwickAveDisplay
      fonts:
        - asset: assets/fonts/SedgwickAveDisplay-Regular.ttf