name: library_of_ohara
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/

  fonts:
    - family: SedgwickAveDisplay
      fonts:
        - asset: assets/fonts/SedgwickAveDisplay-Regular.ttf